### ISSUE TITLE
Is that a joke?

### ISSUE THREAD

**Issue by KrishnaMoorthy12** [PranavGPR/savory-api#7]
Why add localhost links in DOCS? Update production link if you have deployed. 🙃
https://github.com/PranavGPR/savory-api/blob/d39fe027ffb7285b11af9ffc42564ef3071c1fce/README.md#L29

**Comment by PranavGPR** [comment]
> Why add localhost links in DOCS? Update production link if you have deployed. 🙃
> https://github.com/PranavGPR/savory-api/blob/d39fe027ffb7285b11af9ffc42564ef3071c1fce/README.md#L29

For the sake of understanding and also for a reason that I haven't deployed it yet. Thanks for pointing it out. 😀

**Comment by PranavGPR** [comment]
@KrishnaMoorthy12 thanks for reminding me. I've updated the docs, check now.
